name: Nudge Config

server:
  port: :9000
  ui: https://nudgebt.com

bot:
  interval_to_wait:
    unit: h
    time: 1
  next_check_in:
    unit: h
    time: 1

  ignore_bot_prs: true
  skip_days:
    - 0 # sunday
    - 6 # saturday
  follow_up_threshold_comments: 7
  default_timezone: asia/kolkata
  default_business_hours:
    start: 10
    end: 19

github:
  client_id: Iv1.foobar
  client_secret: foobar
  app_id: 1234
  oauth_app_client_id: foobar_id
  oauth_app_client_secret: foobar_secret

slack:
  client_id: '123.456'
  client_secret: foobar

mongo:
  connection: mongodb+srv://username:password@cluster.xx.mongodb.net/?retryWrites=true&w=majority
  database: nudge

aws:
  log_group: "nudge"
  log_stream: "nudge"