name: Nudge Config

server:
  port: :9000
  ui: http://localhost:9000

bot:
  interval_to_wait:
    unit: h
    time: 1
  next_check_in:
    unit: h
    time: 1

  ignore_bot_prs: true
  skip_days:
    - 0 # sunday
    - 6 # saturday
  follow_up_threshold_comments: 7
  default_timezone: Asia/Kolkata
  default_business_hours:
    start: 10
    end: 19

github:
  client_id: abc.xyz
  client_secret: xyz
  app_id: 313280
  oauth_app_client_id: xyz
  oauth_app_client_secret: xyz

slack:
  client_id: '100.200'
  client_secret: xyz

mongo:
  connection: mongodb://nudge:nudge@localhost:27018
  database: nudge